export const dataAtencion = [
  {
    id: 1,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. Volodímir Oleksándrovich Zelenski------------------------------------------------Zelenski Volodímir Oleksándrovich',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 2,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. Rua Dom Francisco Manuel de Melo, 15. 1070-085 Lisbon, Portugal --------------------------------------------------- Rua Dom Francisco Manuel de Melo, 15. 1070-085 Lisbon. Portugal',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 3,
    question:
      'Elige la letra I si las operaciones de cada lado de la igualdad son idénticas, o D si son diferentes. 2+3*5+4-6-3*10 = 2+3*5+4-6-3*10',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 4,
    question:
      'Elige la letra I si las operaciones de cada lado de la igualdad son idénticas, o D si son diferentes. 4+9*7+2-6-6*11 = 4+9*7+6-2-6*11',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 5,
    question:
      'Elige la letra I si las operaciones de cada lado de la igualdad son idénticas, o D si son diferentes. A+F*G+Y-R-E*W = A+F*G+Y-R-E*W',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 6,
    question:
      'Elige la letra I si las operaciones de cada lado de la igualdad son idénticas, o D si son diferentes. C+F*G+B-J-I*W = C+F*G+B-J-L*W',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 7,
    question:
      'Elige la letra I si los signos entre paréntesis son los mismos en ambos grupos, o D si son diferentes. (3$R$#HM) (#3$RHM$)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 8,
    question:
      'Elige la letra I si los signos entre paréntesis son los mismos en ambos grupos, o D si son diferentes. (%1*&S$3) (S%1*B3&)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 9,
    question:
      'Elige la letra I si los grupos de sílabas entre paréntesis son idénticos en ambos grupos, o D si son diferentes. (MA-MI-ME-MO-ME-MU-MA) (ME-MA-MI-ME-MU-MA-MO)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 10,
    question:
      'Elige la letra I si los grupos de sílabas entre paréntesis son idénticos en ambos grupos, o D si son diferentes. (LA-VA-LE-VE-VA-LA-AL) (VA-LA-AV-LE-LA-AL-VE)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 11,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. A+B*C+C-B-C*10 = A+B*C+C-B-C*10',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 12,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. Z+W*K+K-W-K*10 = Z+W*K+K-W-Z*10',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 13,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. PA-AP-PA-AP-PA-AP-PA = PA-AP-PA-AP-PA-AP-PA',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 14,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. DAME-AQUELLO-DAME-AQUELLO-DAME-AQUELLO-DAME = DAME-AQUELLO-DAME-AQUELLO-DAME-AQUELLO-DAME',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 15,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. SISUMAJESTADESSUMAMANONA = SISUMAJESTADESSUMAMANONA',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 16,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. (HAHAKALA-MALAXALA) = (HAHAKALA-MALAKALA)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 17,
    question:
      'Si son idénticos marca en la letra I, si son diferentes en la D. (loremipsumquiadolorsitamet) = (loremipsumquiadolorsitamet)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 18,
    question:
      'Encuentra la acción que corresponde a la secuencia. subebaja-para-sube-baja-baja-parasube-baja-baja-baja- ¿?',
    answer1: 'baja',
    answer2: 'sube',
    answer3: 'para',
    answerC: 'para',
  },
  {
    id: 19,
    question:
      'Encuentra la posición del cursor al final de la secuencia. en medioatrás-adelante-atrás-adelanteadelante-atrás-atrás- ¿?',
    answer1: 'adelante',
    answer2: 'atrás',
    answer3: 'en medio',
    answerC: 'atrás',
  },
  {
    id: 20,
    question:
      'Encuentra el color de la pared al final de la secuencia. gris-blanconegro-gris-negro-negro-blancoblanco- ¿?',
    answer1: 'blanco',
    answer2: 'negro',
    answer3: 'gris',
    answerC: 'gris',
  },
  {
    id: 21,
    question:
      'Encuentra el par de letras que continúan la secuencia. B-B-A-A-CC-B-B-A-A-C-C-B-B-A-A- ¿?',
    answer1: 'B-B',
    answer2: 'A-A',
    answer3: 'C-C',
    answerC: 'C-C',
  },
  {
    id: 22,
    question:
      'Encuentra la terna de letras que continúan la secuencia. LMN-ABCXYZ-LMN-ABC-XYZ-LMN-ABC- ¿?',
    answer1: 'XYZ',
    answer2: 'ABC',
    answer3: 'LMN',
    answerC: 'XYZ',
  },
  {
    id: 23,
    question:
      'Encuentra el conjunto de símbolos que continúan la secuencia. <-->*>--<*|--|*<-->*>--<*|--|*<-->*>--<- ¿?',
    answer1: '|--|',
    answer2: '>--<',
    answer3: '<-->',
    answerC: '|--|',
  },
  {
    id: 24,
    question:
      'Encuentra la respuesta que continúa la secuencia correctamente. <--> A >--< B |--| C <--> D >--< E |--| F <--> G >--<- ¿?',
    answer1: '>--<',
    answer2: '|--|',
    answer3: '<-->',
    answerC: '|--|',
  },
  {
    id: 25,
    question:
      'Encuentra la afirmación correcta para el planteamiento. Luis es mayor que Pedro, Juan es menor que José, Marcelo es menor que Juan y Pedro es mayor que José.',
    answer1: 'Pedro es el mayor de todos.',
    answer2: 'José es menor que Juan.',
    answer3: 'Marcelo es el menor de todos.',
    answer4: 'José es el menor de todos.',
    answerC: 'Marcelo es el menor de todos.',
  },
  {
    id: 26,
    question:
      'Responde correctamente al planteamiento.Si Juan es mayor que Teresa, Teresa mayor que Pedro, Pedro menor que Susana, Pedro mayor que Luis y Susana mayor que Juan. ¿Quién es el mayor?',
    answer1: 'Pedro',
    answer2: 'Juan',
    answer3: 'Teresa',
    answer4: 'Susana',
    answerC: 'Susana',
  },
  {
    id: 27,
    question: 'Encuentra el par de cifras que más disten entre ellas.',
    answer1: '346;789',
    answer2: '765;789',
    answer3: '654;987',
    answer4: '365;764',
    answerC: '346;789',
  },
  {
    id: 28,
    question: 'Encuentra el par de cifras que más se aproximen entre ellas. ',
    answer1: '365;764',
    answer2: '465;789',
    answer3: '654;987',
    answer4: '673;789',
    answerC: '673;789',
  },
  {
    id: 29,
    question:
      'Encuentra el par de números que tanto sumados como multiplicados entre ellos sean un número impar.',
    answer1: '37;45;22',
    answer2: '45;68;42',
    answer3: '34;55;22',
    answer4: '37;53;53',
    answerC: '37;53;53',
  },
  {
    id: 30,
    question: 'Encuentra el par de números que al sumarse den la mayor cifra. ',
    answer1: '628;756',
    answer2: '653;747',
    answer3: '641;778',
    answer4: '673;789',
    answerC: '673;789',
  },
  {
    id: 31,
    question:
      'Elige la letra I si los conjuntos de cifras de dos dígitos entre paréntesis contienen los mismos elementos en ambos grupos, o D si son diferentes. (23-32-24-42-27-72-26) (27-23-32-24-72-26-42)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'I',
  },
  {
    id: 32,
    question:
      'Elige la letra I si los caracteres entre paréntesis son idénticos en ambos grupos, o D si son diferentes. (#S-D%-$A-&N-¿F-/H-¡M) (¿F-#S-P%-$A-/H-¡M-&N)',
    answer1: 'I',
    answer2: 'D',
    answerC: 'D',
  },
  {
    id: 33,
    question: 'Calcula la respuesta correcta. 3+4*3+3-8-10/2',
    answer1: '5',
    answer2: '28',
    answer3: '-9',
    answer4: '11',
    answerC: '5',
  },
  {
    id: 34,
    question: 'Calcula la respuesta correcta. 4+5*2+3-2+10/2',
    answer1: '5',
    answer2: '20',
    answer3: '24',
    answer4: '22',
    answerC: '20',
  },
  {
    id: 35,
    question: 'Calcula la respuesta correcta. (1+2*3+4) -5-6',
    answer1: '1',
    answer2: '-1',
    answer3: '0',
    answer4: '-2',
    answerC: '0',
  },
  {
    id: 36,
    question: 'Calcula la respuesta correcta. 1+2*3+4-5-6 ',
    answer1: '-2',
    answer2: '-1',
    answer3: '1',
    answer4: '0',
    answerC: '0',
  },
  {
    id: 37,
    question: '¿Cuántas X son?3X+4*2X+3X =',
    answer1: '15X',
    answer2: '12X',
    answer3: '23X',
    answer4: '14X',
    answerC: '14X',
  },
  {
    id: 38,
    question: '¿Cuántas rosas son?4 Rosas +5*6 Rosas +3 Rosas -3 =',
    answer1: '38 Rosas',
    answer2: '18 Rosas',
    answer3: '37 Rosas',
    answer4: '34 Rosas',
    answerC: '37 Rosas',
  },
  {
    id: 39,
    question: '¿Cuántas a y b hay en la expresión? 3a+4*3b+3b-8a-2b',
    answer1: '11a + 22b',
    answer2: '-5a + 13b',
    answer3: '-5a + 22b',
    answer4: '11a + 13b',
    answerC: '-5a + 13b',
  },
  {
    id: 40,
    question: '¿Cuántas W y Z hay en la expresión? 4W+5*2Z+3Z-2W-3Z',
    answer1: '6W + 10Z',
    answer2: '6W + 22Z',
    answer3: '2W + 22Z',
    answer4: '2W + 10Z',
    answerC: '2W + 10Z',
  },
];
export const dataRazonamientoL = [
  {
    id: 1,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. da, fa, ha, ja, la,... ',
    answer1: 'na',
    answer2: 'ma',
    answer3: 'pa',
    answer4: 'qa',
    answerC: 'na',
  },
  {
    id: 2,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. dal, lan, nas, sap,...',
    answer1: 'lar',
    answer2: 'mar',
    answer3: 'sar',
    answer4: 'par',
    answerC: 'par',
  },
  {
    id: 3,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. ajop, akoq, alor, amos,... ',
    answer1: 'amov',
    answer2: 'anov',
    answer3: 'amot',
    answer4: 'anot',
    answerC: 'anot',
  },
  {
    id: 4,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. aab, aad, eec, eee, iid, iif,... ,... ',
    answer1: 'ooe, ooh',
    answer2: 'oof, ooh',
    answer3: 'ooe, oog',
    answer4: 'oof, oog',
    answerC: 'ooe, oog',
  },
  {
    id: 5,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. ama, ala, ama, aka, ama,...',
    answer1: 'aja',
    answer2: 'ala',
    answer3: 'aia',
    answer4: 'aka',
    answerC: 'aja',
  },
  {
    id: 6,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. xayaza, xayazax, xayaza, xayazay, xayaza,...',
    answer1: 'xayaza',
    answer2: 'xayazaz',
    answer3: 'xayazayz',
    answer4: 'xayazax',
    answerC: 'xayazaz',
  },
  {
    id: 7,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. ca, le, di, ro, ea, re,...',
    answer1: 'mi',
    answer2: 'ia',
    answer3: 'te',
    answer4: 'wo',
    answerC: 'mi',
  },
  {
    id: 8,
    question:
      'Observa la secuencia y elige la opción que continúa el orden. ca7, le6, di5, ro4, ea3, re2,...',
    answer1: 'me1',
    answer2: 'ia1',
    answer3: 'ti1',
    answer4: 'lo1',
    answerC: 'ti1',
  },
  {
    id: 9,
    question:
      'Encuentra la palabra que continúa la serie. Arroz, Zona, Amor, Robar,...',
    answer1: 'Patear',
    answer2: 'Sazonar',
    answer3: 'Azuzar',
    answer4: 'Rascar',
    answerC: 'Rascar',
  },
  {
    id: 10,
    question:
      'Encuentra la palabra que continúa la serie. Estalla, Anillo, Olla, Allana,...',
    answer1: 'Estrella',
    answer2: 'Challa',
    answer3: 'Coalla',
    answer4: 'Avalla',
    answerC: 'Avalla',
  },
  {
    id: 11,
    question:
      'Encuentra la palabra que continúa la serie. Como, Fomo, Romo,...',
    answer1: 'Pomo',
    answer2: 'Tomo',
    answer3: 'Homo',
    answer4: 'Lomo',
    answerC: 'Tomo',
  },
  {
    id: 12,
    question:
      'Encuentra la opción que expresa la relación entre las palabras. Comer es a amor, como:',
    answer1: 'Beber es a dolor',
    answer2: 'Reír es a querer',
    answer3: 'Sentir es a amar',
    answer4: 'Hablar es a abrazar',
    answerC: 'Beber es a dolor',
  },
  {
    id: 13,
    question:
      'Encuentra la palabra que no corresponde al grupo. Tieso, Evito, Queso, Siervo',
    answer1: 'Siervo',
    answer2: 'Tieso',
    answer3: 'Evito',
    answer4: 'Queso',
    answerC: 'Queso',
  },
  {
    id: 14,
    question:
      'Encuentra la palabra que pertenece al grupo. Ayudó, Valuó, Anudó',
    answer1: 'Acoso',
    answer2: 'Arrimó',
    answer3: 'Pautó',
    answer4: 'Ahorró',
    answerC: 'Pautó',
  },
  {
    id: 15,
    question: 'Calcula el siguiente valor en la serie: 1, 3, 4, 7, 11,...',
    answer1: '19',
    answer2: '17',
    answer3: '18',
    answer4: '16',
    answerC: '18',
  },
  {
    id: 16,
    question:
      'Calcula el siguiente valor en la serie: 1, 3, 3, 5, 5, 7, 7, 9,..',
    answer1: '10',
    answer2: '7',
    answer3: '11',
    answer4: '9',
    answerC: '9',
  },
  {
    id: 17,
    question: 'Calcula el siguiente elemento de la serie: CE, EG, GI, IK,... ',
    answer1: 'KJ',
    answer2: 'KL',
    answer3: 'KN',
    answer4: 'KM',
    answerC: 'KM',
  },
  {
    id: 18,
    question: 'Calcula el siguiente elemento de la serie: B3, E6, H9, K12,... ',
    answer1: 'L15',
    answer2: 'N15',
    answer3: 'M15',
    answer4: 'O15',
    answerC: 'N15',
  },
  {
    id: 19,
    question: 'Calcula el siguiente valor en la serie: 3, 4, 14, 36,... ',
    answer1: '80',
    answer2: '100',
    answer3: '120',
    answer4: '110',
    answerC: '100',
  },
  {
    id: 20,
    question: 'Calcula el siguiente valor en la serie: 6, 7, 113, 220,...',
    answer1: '423',
    answer2: '433',
    answer3: '443',
    answer4: '440',
    answerC: '433',
  },
  {
    id: 21,
    question: 'Calcula el valor correcto: 3, 4, 5 es a 12 como 5, 12, 21 es a',
    answer1: '39',
    answer2: '37',
    answer3: '38',
    answer4: '40',
    answerC: '38',
  },
  {
    id: 22,
    question: 'Calcula el siguiente valor en la serie: 6, 8, 12, 20, 36,... ',
    answer1: '66',
    answer2: '68',
    answer3: '70',
    answer4: '72',
    answerC: '68',
  },
  {
    id: 23,
    question:
      'Encuentra la respuesta correcta. Si A=$3, B=$4, C=$5, ¿cuánto es 12-B-C?',
    answer1: 'A',
    answer2: 'A-1',
    answer3: 'A+1',
    answer4: 'C-B',
    answerC: 'A',
  },
  {
    id: 24,
    question:
      'Encuentra la respuesta correcta. Si X=6, Y=4, Z=7, ¿cuánto es 336/Y*Z?',
    answer1: '2X',
    answer2: '2Y',
    answer3: '2Z',
    answer4: 'Z-Y',
    answerC: '2X',
  },
  {
    id: 25,
    question:
      'Encuentra la respuesta correcta. Si inicialmente una manecilla de reloj marca las 12.00 y después gira 50° a la izquierda, luego 40° a la derecha, después 35° a la izquierda y finalmente 45° a la derecha, ¿qué hora marca el reloj en su posición final?',
    answer1: '01:00',
    answer2: '12:00',
    answer3: '11:00',
    answer4: '00:10',
    answerC: '12:00',
  },
  {
    id: 26,
    question:
      'Encuentra la respuesta correcta. Si A=2, B=6, C=23, ¿cuánto es A+B+C-3B?',
    answer1: '7',
    answer2: '13',
    answer3: '19',
    answer4: '28',
    answerC: '13',
  },
  {
    id: 27,
    question:
      'Encuentra la respuesta correcta. Si X=10, Y=10, Z=3, ¿cuánto es X*Y*Z/5Y?',
    answer1: '600',
    answer2: '60',
    answer3: '6',
    answer4: '3',
    answerC: '6',
  },
  {
    id: 28,
    question:
      'Calcula la respuesta correcta. Si $12 - $4 - $6 + $15 + 2*$5 = 1 viaje, ¿cuánto cuesta 1 viaje?',
    answer1: '$15',
    answer2: '$11',
    answer3: '$27',
    answer4: '$16',
    answerC: '$27',
  },
  {
    id: 29,
    question:
      'Selecciona el conjunto de letras que no pertenece al grupo. CILAKXJ',
    answer1: 'CALIKXJ',
    answer2: 'CXLAKIJ',
    answer3: 'CALXKLJ',
    answer4: 'CALXKIJ',
    answerC: 'CALXKLJ',
  },
  {
    id: 30,
    question:
      'Selecciona el conjunto de letras que no pertenece al grupo. QYLZKXJ',
    answer1: 'QZLXKYJ',
    answer2: 'QXLZKYJ',
    answer3: 'QZLYKXJ ',
    answer4: 'QZLXKLJ',
    answerC: 'QZLXKLJ',
  },
  {
    id: 31,
    question:
      'Selecciona el número que completa la serie correctamente. A, -4, C, -8, E, -16, G, __ ',
    answer1: '-32',
    answer2: '-34',
    answer3: '-30',
    answer4: '-64',
    answerC: '-32',
  },
  {
    id: 32,
    question:
      'Selecciona el número que completa la serie correctamente. 8, -4, 4, 0, 4, 4, __ ',
    answer1: '8',
    answer2: '4',
    answer3: '0',
    answer4: '-8',
    answerC: '8',
  },
  {
    id: 33,
    question:
      'Selecciona la opción que completa la serie correctamente. AC, 4, BD, 6, CE, 8, _ ',
    answer1: 'EF',
    answer2: 'DG',
    answer3: 'DF',
    answer4: 'EG',
    answerC: 'DF',
  },
  {
    id: 34,
    question:
      'Selecciona la opción que completa la serie correctamente. PR, 4, QS, 6, RT, 8, SU, 10, __ ',
    answer1: 'SV',
    answer2: 'UW',
    answer3: 'TV',
    answer4: 'TU',
    answerC: 'TV',
  },
  {
    id: 35,
    question:
      'Selecciona el número que completa la serie correctamente. 1, -4, 2, -8, 3, -16, 4, __',
    answer1: '5',
    answer2: '-34',
    answer3: '-30',
    answer4: '-32',
    answerC: '-32',
  },
  {
    id: 36,
    question:
      'Selecciona el número que completa la serie correctamente. 4, -4, 6, -9, 8, -19, 10, __',
    answer1: '12',
    answer2: '-41',
    answer3: '-37',
    answer4: '-39',
    answerC: '-39',
  },
  {
    id: 37,
    question: 'Completa la serie correctamente. A, 80, D, 120, G, 180, _ , _ ',
    answer1: 'M, 270',
    answer2: 'J, 360',
    answer3: 'M, 360',
    answer4: 'J, 270',
    answerC: 'J, 270',
  },
  {
    id: 38,
    question: 'Completa la serie correctamente. 10, - 4, 6, 2, 8, 10, __ ',
    answer1: '8',
    answer2: '16',
    answer3: '20',
    answer4: '18',
    answerC: '18',
  },
  {
    id: 39,
    question:
      'Selecciona el número que completa la serie correctamente. AC, 4, BD, 6, CE, 8, DF, __ ',
    answer1: '9',
    answer2: '10',
    answer3: '8',
    answer4: '11',
    answerC: '10',
  },
  {
    id: 40,
    question:
      'Selecciona el número que completa la serie correctamente. 0, 2, 4, 10, 24, 58, __',
    answer1: '140',
    answer2: '164',
    answer3: '150',
    answer4: '130',
    answerC: '140',
  },
];
export const dataRazonamientoV = [
  {
    id: 1,
    question:
      'Encuentra la palabra que más se asemeja al significado del concepto resaltado en mayúsculas. Actuó con PASIÓN.',
    answer1: 'Vehemencia',
    answer2: 'Talento',
    answer3: 'Fuerza',
    answer4: 'Motivo',
    answerC: 'Vehemencia',
  },
  {
    id: 2,
    question:
      'Encuentra la palabra que más se asemeja al significado del concepto resaltado en mayúsculas.Promovió la COMPARACIÓN.',
    answer1: 'Admisión',
    answer2: 'Medición',
    answer3: 'Contrastación',
    answer4: 'Conceptualización',
    answerC: 'Contrastación',
  },
  {
    id: 3,
    question: 'Elige la palabra que más se acerca al significado de: Consensúa',
    answer1: 'Establece',
    answer2: 'Apoya',
    answer3: 'Corrobora',
    answer4: 'Acuerda',
    answerC: 'Acuerda',
  },
  {
    id: 4,
    question: 'Elige la palabra que más se acerca al significado de: Ostenta',
    answer1: 'Avienta',
    answer2: 'Pretende',
    answer3: 'Exime',
    answer4: 'Exhibe',
    answerC: 'Exhibe',
  },
  {
    id: 5,
    question: 'Elige la palabra que más se aleja del significado de: Inerte',
    answer1: 'Enérgico',
    answer2: 'Divertido',
    answer3: 'Alegre',
    answer4: 'Dinámico',
    answerC: 'Dinámico',
  },
  {
    id: 6,
    question: 'Elige la palabra que más se acerca al significado de: Interino',
    answer1: 'Provisional',
    answer2: 'Permanente',
    answer3: 'Hipotético',
    answer4: 'Peculiar',
    answerC: 'Provisional',
  },
  {
    id: 7,
    question: 'Elige la palabra que más se acerca al significado de: Desear',
    answer1: 'Preferir',
    answer2: 'Apetecer',
    answer3: 'Elegir',
    answer4: 'Tener',
    answerC: 'Apetecer',
  },
  {
    id: 8,
    question: 'Elige la palabra que más se acerca al significado de: Ansiar',
    answer1: 'Estimar',
    answer2: 'Desear',
    answer3: 'Adorar',
    answer4: 'Venerar',
    answerC: 'Desear',
  },
  {
    id: 9,
    question: 'Elige la palabra que más se aleja del significado de: Menguado',
    answer1: 'Parco',
    answer2: 'Ruin',
    answer3: 'Ofensivo',
    answer4: 'Miserable',
    answerC: 'Ofensivo',
  },
  {
    id: 10,
    question: 'Elige la palabra que más se aleja del significado de: Usurero',
    answer1: 'Mezquino',
    answer2: 'Ambicioso',
    answer3: 'Miserable',
    answer4: 'Desastroso',
    answerC: 'Desastroso',
  },
  {
    id: 11,
    question:
      'Elige el par de palabras que completan la oración correctamente.Ese aroma _________ más que las orquídeas, su _________ era dulce, como la miel.',
    answer1: 'cautivaba-fragancia',
    answer2: 'fragante-cautiva',
    answer3: 'cautiva-caminaba',
    answer4: 'cautivaba-fragante',
    answerC: 'cautivaba-fragancia',
  },
  {
    id: 12,
    question:
      'Elige el par de palabras que completan la oración correctamente.Comía _________ que un pájaro, su _________ vocación era leer',
    answer1: 'menos-una',
    answer2: 'únicamente-menor',
    answer3: 'menor-única',
    answer4: 'menos-única',
    answerC: 'menos-única',
  },
  {
    id: 13,
    question:
      'Elige el par de palabras que completan la oración correctamente.Pesaba _________ que una pluma, su _________ valor era sentimental.',
    answer1: 'más-única',
    answer2: 'únicamente-mayor',
    answer3: 'más-mayor',
    answer4: 'más-muy',
    answerC: 'más-mayor',
  },
  {
    id: 14,
    question:
      'Elige el par de palabras que completan la oración correctamente.Hablaba _________ que un erudito, su _________ desafío era soñar.',
    answer1: 'mejor-mayor',
    answer2: 'mayor-mejor',
    answer3: 'tanto-mal',
    answer4: 'menos-bueno',
    answerC: 'mejor-mayor',
  },
  {
    id: 15,
    question:
      'Elige el par de palabras que completan la oración correctamente.Vivió _________ un bribón, su  _________ consistió en timar.',
    answer1: 'creando-vivió',
    answer2: 'porque-vida',
    answer3: 'como-vida',
    answer4: 'como-vivida',
    answerC: 'como-vida',
  },
  {
    id: 16,
    question: 'Encuentra la palabra que no pertenece a la categoría.',
    answer1: 'Campestres',
    answer2: 'Campesinas',
    answer3: 'Campeonato',
    answer4: 'Campearías',
    answerC: 'Campeonato',
  },
  {
    id: 17,
    question: 'Encuentra la palabra que no pertenece a la categoría.',
    answer1: 'Atravesasen',
    answer2: 'Atravesaremos',
    answer3: 'Atravesáramos',
    answer4: 'Atravesarías',
    answerC: 'Atravesaremos',
  },
  {
    id: 18,
    question: 'Encuentra la palabra que no pertenece a la categoría.',
    answer1: 'Campásemos',
    answer2: 'Campearemos',
    answer3: 'Campáramos',
    answer4: 'Campearían',
    answerC: 'Campearemos',
  },
  {
    id: 19,
    question: 'Encuentra la palabra que no pertenece a la categoría.',
    answer1: 'Condesas',
    answer2: 'Concedas',
    answer3: 'Condenas',
    answer4: 'Conciben',
    answerC: 'Conciben',
  },
  {
    id: 20,
    question: 'Encuentra la palabra que no pertenece a la categoría.',
    answer1: 'Las trabes trababan el techo.',
    answer2: 'Los tratantes trataban los negocios.',
    answer3: 'Los tramadores tramaban guerras.',
    answer4: 'Los tragones tragaban fuego.',
    answerC: 'Las trabes trababan el techo.',
  },
  {
    id: 21,
    question: 'Encuentra la palabra que no pertenece a la categoría.',
    answer1: 'Pretensión',
    answer2: 'Presentación',
    answer3: 'Premiación',
    answer4: 'Prelación',
    answerC: 'Pretensión',
  },
  {
    id: 22,
    question:
      'Elige el par de palabras que asemejan la relación entre:Comer-Cenar',
    answer1: 'Sufrir-Llorar',
    answer2: 'Latir-Sentir',
    answer3: 'Conversar-Animar',
    answer4: 'Entender-Comprender',
    answerC: 'Entender-Comprender',
  },
  {
    id: 23,
    question:
      'Elige el par de palabras que asemejan la relación entre:Inventar-Innovar',
    answer1: 'Estrenar-Inaugurar',
    answer2: 'Atraer-Insinuar',
    answer3: 'Elevar-Trepar',
    answer4: 'Querer-Desear',
    answerC: 'Estrenar-Inaugurar',
  },
  {
    id: 24,
    question:
      'Elige el par de palabras que asemejan la relación entre:Ocultar-Esconder',
    answer1: 'Postergar-Proponer',
    answer2: 'Abandonar-Dejar',
    answer3: 'Desconocer-Desatender',
    answer4: 'Omitir-Olvidar',
    answerC: 'Abandonar-Dejar',
  },
  {
    id: 25,
    question:
      'Elige el par de palabras que asemejan la relación entre:Postergar-Posponer',
    answer1: 'Ceñir-Ajustar',
    answer2: 'Apretar-Moderar',
    answer3: 'Limitar-Rodear',
    answer4: 'Razonar-Admitir',
    answerC: 'Ceñir-Ajustar',
  },
  {
    id: 26,
    question:
      'Elige el par de palabras que difieren de la relación entre:Animar-Dinamizar',
    answer1: 'Lustrar-Sobar',
    answer2: 'Limar-Picar',
    answer3: 'Lijar-Pulir',
    answer4: 'Arrugar-Plegar',
    answerC: 'Lijar-Pulir',
  },
  {
    id: 27,
    question:
      'Sustituye la palabra en mayúscula para dar un sentido opuesto a la oración.Y ellos lo ABANDONARON en el páramo.',
    answer1: 'Protegieron',
    answer2: 'Celebraron',
    answer3: 'Ampararon',
    answer4: 'Abrigaron',
    answerC: 'Ampararon',
  },
  {
    id: 28,
    question:
      'Sustituye la palabra en mayúscula para dar un sentido opuesto a la oración. El color del agua es AMBIGUO.',
    answer1: 'Turbio',
    answer2: 'Transparente',
    answer3: 'Dependiente',
    answer4: 'Preciso',
    answerC: 'Preciso',
  },
  {
    id: 29,
    question:
      'Sustituye la palabra en mayúscula para dar un sentido opuesto a la oración. La DISCORDIA general era por la injusticia.',
    answer1: 'Admiración',
    answer2: 'Inteligencia',
    answer3: 'Avenencia',
    answer4: 'Alternancia',
    answerC: 'Avenencia',
  },
  {
    id: 30,
    question:
      'Elige la palabra que da sentido a la oración.Los nativos ____________ la tierra y cosechaban frutos.',
    answer1: 'Talaban',
    answer2: 'Cortaban',
    answer3: 'Cultivaban',
    answer4: 'Mondaban',
    answerC: 'Cultivaban',
  },
  {
    id: 31,
    question:
      'Elige la palabra que cambia el sentido a la oración. Cuando jugaban, todos provocaban:',
    answer1: 'Contiendas',
    answer2: 'Apuros',
    answer3: 'Luchas',
    answer4: 'Batallas',
    answerC: 'Apuros',
  },
  {
    id: 32,
    question:
      'Sustituye la palabra en mayúscula para dar un sentido opuesto a la oración.Esa mascota era la más ASEADA de todas.',
    answer1: 'Despreciada',
    answer2: 'Fea',
    answer3: 'Inmunda',
    answer4: 'Incómoda',
    answerC: 'Inmunda',
  },
  {
    id: 33,
    question:
      'Elige la palabra que no comparte el mismo significado que las demás.',
    answer1: 'Valiente',
    answer2: 'Valeroso',
    answer3: 'Mesurado',
    answer4: 'Atrevido',
    answerC: 'Mesurado',
  },
  {
    id: 34,
    question:
      'Elige la palabra que no comparte el mismo significado que las demás.',
    answer1: 'Pretender',
    answer2: 'Conquistar',
    answer3: 'Cortejar',
    answer4: 'Conversar',
    answerC: 'Conversar',
  },
  {
    id: 35,
    question:
      'Elige la palabra que no pertenece a la misma categoría de las demás.',
    answer1: 'Hablar',
    answer2: 'Gritar',
    answer3: 'Sonreír',
    answer4: 'Gruñir',
    answerC: 'Sonreír',
  },
  {
    id: 36,
    question:
      'Elige la palabra que no pertenece a la misma categoría de las demás.',
    answer1: 'Descubrir',
    answer2: 'Erigir',
    answer3: 'Crear',
    answer4: 'Engendrar',
    answerC: 'Descubrir',
  },
  {
    id: 37,
    question:
      'Elige la palabra que no comparte el mismo significado que las demás',
    answer1: 'Remover',
    answer2: 'Exterminar',
    answer3: 'Aniquilar',
    answer4: 'Masacrar',
    answerC: 'Remover',
  },
  {
    id: 38,
    question:
      'Elige la palabra que no comparte el mismo significado que las demás.',
    answer1: 'Atrevido',
    answer2: 'Valeroso',
    answer3: 'Valiente',
    answer4: 'Prudente',
    answerC: 'Prudente',
  },
  {
    id: 39,
    question:
      '¿Cuál de las siguientes palabras está escrita sin faltas de ortografía?',
    answer1: 'Asunción',
    answer2: 'Colución',
    answer3: 'Precición',
    answer4: 'Abración',
    answerC: 'Asunción',
  },
  {
    id: 40,
    question: 'Elige la palabra que no pertenece a la categoría.',
    answer1: 'Acusación',
    answer2: 'Munición',
    answer3: 'Licitación',
    answer4: 'Maldición',
    answerC: 'Munición',
  },
];
export const dataRazonamientoN = [
  {
    id: 1,
    question:
      'Calcula la solución al siguiente planteamiento. Una persona tiene $260 en cinco cupones y cuatro de ellos son de $45 cada uno, ¿de cuánto es el otro cupón?',
    answer1: '$80',
    answer2: '$90',
    answer3: '$70',
    answer4: '$215',
    answerC: '$80',
  },
  {
    id: 2,
    question:
      'Encuentra la respuesta correcta al planteamiento. Usted tiene 20 pelotas, regala 4, le roban 3, pierde 5 y compra otras 4. Si divide en partes iguales, ¿cuántas pelotas recibirá cada uno de los 4 niños a los que debe entregar?',
    answer1: '3',
    answer2: '2',
    answer3: '4',
    answer4: '1',
    answerC: '3',
  },
  {
    id: 3,
    question:
      'Encuentra la respuesta correcta al planteamiento. En una competencia corre 18 km, camina 9 km; nada 2000 metros más, conduce en bicicleta otros 5000 metros. ¿De cuántos kilómetros fue su recorrido?',
    answer1: '32',
    answer2: '33',
    answer3: '35',
    answer4: '34',
    answerC: '34',
  },
  {
    id: 4,
    question:
      'Encuentra la respuesta correcta al planteamiento. En un hogar se utilizan 340 litros de agua, 190 litros se utilizan para bañarse; se lavan platos y ropa con 34 litros; se lavan los autos con el 5% y lo mismo se emplea en el jardín. ¿Cuántos litros se utilizan para el jardín? ',
    answer1: '18',
    answer2: '16',
    answer3: '17',
    answer4: '34',
    answerC: '17',
  },
  {
    id: 5,
    question:
      'Encuentra la respuesta correcta al planteamiento. Una familia compra 100 tacos. El 42% de ellos eran de carne, el 35% eran de pollo y los demás de queso, ¿cuántos eran de queso?',
    answer1: '32',
    answer2: '77',
    answer3: '76',
    answer4: '23',
    answerC: '23',
  },
  {
    id: 6,
    question:
      'Encuentra la respuesta correcta al planteamiento. Para cenar, unos amigos piden 7 pizzas. Cada pizza tiene 8 rebanadas. Se comen el 64% en el restaurante, se llevan a casa el 23% y dejan lo demás. ¿Cuánto dejaron?',
    answer1: '88%',
    answer2: '12%',
    answer3: '87%',
    answer4: '13%',
    answerC: '13%',
  },
  {
    id: 7,
    question:
      'Encuentra la respuesta correcta al planteamiento. Un auto avanza 16 kilómetros, luego retrocede 800 metros, vuelve a avanzar 3 kilómetros, ¿cuántos metros avanzó realmente?',
    answer1: '18200',
    answer2: '1200',
    answer3: '17200',
    answer4: '19200',
    answerC: '18200',
  },
  {
    id: 8,
    question:
      'Encuentra la respuesta correcta al planteamiento. Una nave espacial, que puede viajar a 900 millas por hora, se mantiene en la base durante 9 horas desde las 04:00 am. Cuando despega, se desplaza a 750 millas por hora, ¿cuántas millas llevará recorridos a las 9:00 pm?',
    answer1: '6750',
    answer2: '6000',
    answer3: '7200',
    answer4: '12750',
    answerC: '6000',
  },
  {
    id: 9,
    question:
      'Encuentra la respuesta correcta al planteamiento. Un avión hace 10 vuelos por mes. Cada mes, el piloto revisa 9 veces los controles, 8 los alerones, 11 el combustible. En cinco meses, ¿cuántas veces habrá revisado los controles, los alerones y el combustible, respectivamente?',
    answer1: '45, 40, 55',
    answer2: '55, 40, 45',
    answer3: '45, 55, 40 ',
    answer4: '90, 80, 110',
    answerC: '45, 40, 55',
  },
  {
    id: 10,
    question:
      'Encuentra la respuesta correcta al planteamiento. Si Pedro tiene 12 años y su madre cuatro veces la edad que él. Cuando Pedro tenga 23 años, ¿cuántos tendrá su madre?',
    answer1: '58',
    answer2: '48',
    answer3: '59',
    answer4: '92',
    answerC: '59',
  },
  {
    id: 11,
    question:
      'Encuentra la respuesta correcta al planteamiento. Varias familias van de paseo en 12 autos. Cinco autos llevan familias de 4 personas cada uno. En tres autos viajan tres personas y cuatro van ocupados por solo dos personas.¿Cuántas personas viajan en total?',
    answer1: '35',
    answer2: '36',
    answer3: '37',
    answer4: '38',
    answerC: '37',
  },
  {
    id: 12,
    question:
      'Encuentra el porcentaje correcto. Una espada está compuesta de 5 elementos: 14% de Zinc, 18% de Hierro, 13% de Carbono y 12% de Estaño, ¿cuál será el porcentaje de Bronce que posee?',
    answer1: '57%',
    answer2: '43%',
    answer3: '47%',
    answer4: '53%',
    answerC: '43%',
  },
  {
    id: 13,
    question:
      'Encuentra el porcentaje correcto. Diariamente, el 55% del Ecovía va ocupado por hombres menores de 65 y el 25% por mujeres menores de 65. Del restante, 30% son mujeres, ¿qué porcentaje del total representan?',
    answer1: '14%',
    answer2: '6%',
    answer3: '8%',
    answer4: '30%',
    answerC: '6%',
  },
  {
    id: 14,
    question:
      'Encuentra el porcentaje correcto. El cuerpo humano está hecho de elementos químicos. Si 65% es Oxígeno, 19% Carbono, 11% Hidrógeno y 3% Nitrógeno, ¿cuánto es el porcentaje restante para los demás elementos? ',
    answer1: '98%',
    answer2: '95%',
    answer3: '2%',
    answer4: '3%',
    answerC: '2%',
  },
  {
    id: 15,
    question:
      'Encuentra el porcentaje correcto. Si un profesional gasta 32,5% de su salario en vivienda, 26,5% en comida, 16,5% en salud y 8,5% en educación, ¿de cuánto puede disponer para sus demás gastos? ',
    answer1: '15%',
    answer2: '84%',
    answer3: '74%',
    answer4: '16%',
    answerC: '16%',
  },
  {
    id: 16,
    question:
      'Calcula la respuesta correcta. Si una cama cuesta $300, un velador $60 y una silla $670, ¿cuánto debe pagarse por 3 camas, 6 veladores y 2 sillas? ',
    answer1: '3200',
    answer2: '2600',
    answer3: '1030',
    answer4: '2700',
    answerC: '2600',
  },
  {
    id: 17,
    question:
      'Calcula la respuesta correcta.Si un viaje individual a Esmeraldas cuesta $400, uno a Manta $550 y uno a Galápagos $880, ¿cuánto costaría a una pareja hacer los 3 viajes en un año? ',
    answer1: '3660',
    answer2: '3560',
    answer3: '3760',
    answer4: '1830',
    answerC: '3660',
  },
  {
    id: 18,
    question:
      'Calcula el valor correcto para el planteamiento. La nota final de Juan en Matemáticas es de 9,5 y se calcula como el promedio de las notas de los tres exámenes parciales. Si en el primer examen obtuvo 9,2 y en el segundo 9,4, ¿cuál fue su nota en el tercer examen?',
    answer1: '9,9',
    answer2: '10,0',
    answer3: '9,6',
    answer4: '9,7',
    answerC: '9,9',
  },
  {
    id: 19,
    question:
      'Calcula el valor correcto para el planteamiento. Un patio de autos tiene 120 unidades, el 45% de ellos son rojos y el 5% negros. ¿Cuántos autos de cada color hay?',
    answer1: '54 rojos y 6 negros',
    answer2: '45 rojos y 5 negros',
    answer3: '54 rojos y 5 negros',
    answer4: '45 rojos y 6 negros',
    answerC: '54 rojos y 6 negros',
  },
  {
    id: 20,
    question:
      'Calcula el valor correcto para el planteamiento. En el colegio "Rockero", a 40 de sus 80 estudiantes les gusta la cumbia. En el colegio "Salsero" hay 60 estudiantes y a 45 les gusta la cumbia. En el colegio "Cumbiero" hay 100 estudiantes y a 30 les gusta la cumbia. ¿En qué colegio hay mayor porcentaje de gusto por la cumbia?',
    answer1: '"Cumbiero" y "Rockero"',
    answer2: '"Cumbiero" ',
    answer3: ' "Rockero"',
    answer4: '"Salsero"',
    answerC: '"Salsero"',
  },
  {
    id: 21,
    question:
      'Calcula el valor correcto para el planteamiento. Los estudiantes aciertan en el 60% de las preguntas de una prueba nacional. Si la prueba tiene un total de 150 preguntas, en promedio, ¿en cuántas preguntas se espera que no acierten? ',
    answer1: '90',
    answer2: '60',
    answer3: '65',
    answer4: '40',
    answerC: '60',
  },
  {
    id: 22,
    question:
      'Calcula el valor correcto para el planteamiento. El 18% de los anuncios en una ciudad son luminosos. Si en la ciudad hay 4500 anuncios, ¿cuántos anuncios no luminosos hay en toda la ciudad?',
    answer1: '810',
    answer2: '3690',
    answer3: '82%',
    answer4: '800',
    answerC: '3690',
  },
  {
    id: 23,
    question:
      'Calcula el valor correcto para el planteamiento. El ingreso mensual de un especialista es de $1200. Al ascender a Coordinador, su sueldo aumentará 35%. ¿Cuál será su nuevo ingreso mensual? ',
    answer1: '1420',
    answer2: '1620',
    answer3: '1350',
    answer4: '1520',
    answerC: '1620',
  },
  {
    id: 24,
    question:
      'Calcula el valor correcto para el planteamiento. El ingreso promedio mensual de tres hermanos es de $1900. El mayor tiene un sueldo de $1500, el segundo gana $1200. ¿Cuál será el sueldo del hermano menor?',
    answer1: '1350',
    answer2: '1900',
    answer3: '3000',
    answer4: '3100',
    answerC: '3000',
  },
  {
    id: 25,
    question:
      'Encuentra la respuesta correcta. Si Flor=$3, Rosa=$27, Planta=$81, ¿cuántas rosas se pueden comprar por cada planta? ',
    answer1: '3',
    answer2: '9',
    answer3: '27',
    answer4: '26',
    answerC: '3',
  },
  {
    id: 26,
    question:
      'Encuentra la respuesta correcta. Los 2/5 de un número es 80, ¿cuánto será los 3/10 del mismo número?',
    answer1: '200',
    answer2: '32',
    answer3: '168',
    answer4: '60',
    answerC: '60',
  },
  {
    id: 27,
    question:
      'Encuentra la respuesta correcta. Se vendió una camisa con una ganancia del 15% sobre el precio de costo. Si se ha vendido en $92, hallar el precio de costo.',
    answer1: '81',
    answer2: '78',
    answer3: '80',
    answer4: '79',
    answerC: '80',
  },
  {
    id: 28,
    question:
      'Encuentra la respuesta correcta. Si el dólar se devaluará cada año 8%. ¿Qué porcentaje de su valor inicial en 2022 tendrá al finalizar el año 2024?',
    answer1: '68%',
    answer2: '76%',
    answer3: '84%',
    answer4: '78%',
    answerC: '78%',
  },
  {
    id: 29,
    question:
      'Encuentra la respuesta correcta. Al adquirir una lancha, cuyo precio es de $8000, nos hacen un descuento del 20%, ¿cuánto hay que pagar por el vehículo?',
    answer1: '8020',
    answer2: '6500',
    answer3: '6400',
    answer4: '6399',
    answerC: '6400',
  },
  {
    id: 30,
    question:
      'Encuentra la respuesta correcta. Si 8 personas se comen 40 bocaditos en 15 minutos, ¿cuánto demorarán 10 personas en comer la misma cantidad?',
    answer1: '13',
    answer2: '12',
    answer3: '10',
    answer4: '11',
    answerC: '12',
  },
  {
    id: 31,
    question:
      'Encuentra la respuesta correcta. El 20% de 9 horas es equivalente en minutos a:',
    answer1: '108',
    answer2: '20',
    answer3: '109',
    answer4: '432',
    answerC: '108',
  },
  {
    id: 32,
    question:
      'Encuentra la respuesta correcta. El 20% de 70 semanas equivale a _____ días',
    answer1: '196',
    answer2: '14',
    answer3: '20',
    answer4: '98',
    answerC: '98',
  },
  {
    id: 33,
    question:
      'Selecciona la respuesta correcta al planteamiento. Si una motocicleta avanza a 120 km/h durante 40 minutos y luego a 90 km/h durante 20 minutos, ¿cuántos kilómetros recorre durante su trayecto?',
    answer1: '110',
    answer2: '210',
    answer3: '105',
    answer4: '120',
    answerC: '110',
  },
  {
    id: 34,
    question:
      'Selecciona la respuesta correcta al planteamiento. Una persona camina durante 40 minutos a 9 km/h, luego pausa 3 minutos y corre otros 10 minutos a 6 km/h, ¿cuántos kilómetros habrá recorrido durante ese tiempo? ',
    answer1: '6',
    answer2: '8',
    answer3: '7',
    answer4: '9',
    answerC: '7',
  },
  {
    id: 35,
    question:
      'Selecciona la respuesta correcta al planteamiento. Un automóvil va a una velocidad de 50 km/h y se detiene 6 minutos cada hora. Si circula durante 8 horas, ¿cuántos kilómetros recorre en ese tiempo?',
    answer1: '360',
    answer2: '400',
    answer3: '340',
    answer4: '376',
    answerC: '360',
  },
  {
    id: 36,
    question:
      'Selecciona la respuesta correcta al planteamiento.Un auto de carreras va a una velocidad de 180 km/h y uno urbano lo hace a 90 km/h. Después de 7 horas, ¿cuántos kilómetros habrá de diferencia entre ambos?',
    answer1: '540',
    answer2: '630',
    answer3: '720',
    answer4: '675',
    answerC: '630',
  },
  {
    id: 37,
    question:
      'Selecciona la respuesta correcta al planteamiento. En una jornada de 8 horas se pintan 16 metros cuadrados de pared y se emplean 3 litros de pintura, ¿cuántas horas y cuánta pintura se requerirá para pintar una pared de 40 metros cuadrados?',
    answer1: '20 horas y 7,5 litros de pintura',
    answer2: '80 horas y 8 litros de pintura',
    answer3: '40 horas y 6,5 litros de pintura',
    answer4: '24 horas y 8,5 litros de pintura',
    answerC: '20 horas y 7,5 litros de pintura',
  },
  {
    id: 38,
    question:
      'Selecciona la respuesta correcta al planteamiento. El precio de un par de lámparas es de $1200 sin IVA. ¿Cuánto hay que pagar por cada una si el IVA fuera del 12%?',
    answer1: '744',
    answer2: '600',
    answer3: '662',
    answer4: '672',
    answerC: '672',
  },
  {
    id: 39,
    question:
      'Selecciona la respuesta correcta al planteamiento. Se desea distribuir 338 esferos, 364 cuadernos, 260 libros y 962 lápices entre 26 estudiantes en forma equitativa, ¿cuántos esferos, cuadernos, libros y lápices les tocaría a cada uno?',
    answer1: '13 esferos, 14 cuadernos, 10 libros y 37 lápices',
    answer2: '12 esferos, 14 cuadernos, 10 libros y 37 lápices',
    answer3: '13 esferos, 14 cuadernos, 9 libros y 37 lápices',
    answer4: '13 esferos, 14 cuadernos, 10 libros y 36 lápices',
    answerC: '13 esferos, 14 cuadernos, 10 libros y 37 lápices',
  },
  {
    id: 40,
    question:
      'Selecciona la respuesta correcta al planteamiento. Luis tiene el doble de ahorro que Jorge, si entre ambos desean comprar un auto de $12.000, Luis debería tener el doble de dinero que tiene. ¿Cuánto dinero tiene Jorge?',
    answer1: '2400',
    answer2: '2000',
    answer3: '3000',
    answer4: '4000',
    answerC: '2400',
  },
];
